application:
  author:
    names: james yoyo
    address: ShangHai city
    email: 103xxxxx@qq.com
  date: 2019/07

spring:
  redis:
    host: wk-server
    password: ${SECURITY_USER_PASSWORD}
    database: 0
  eureka_server_hostname: jr-server
  eureka_server: http://admin:${SECURITY_USER_PASSWORD}@${spring.eureka_server_hostname}:2001/eureka/,http://admin:${SECURITY_USER_PASSWORD}@${spring.eureka_server_hostname}:2002/eureka/,http://admin:${SECURITY_USER_PASSWORD}@${spring.eureka_server_hostname}/eureka/

security:
    user:
        name: admin
        password: ${SECURITY_USER_PASSWORD}
# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true
