application:
  author:
    names: james yoyo
    address: ShangHai city
    email: 103xxxxx@qq.com
  date: 2019/07
spring:
  redis:
    host: ${redisserver:jr-server}
    #没有密码可以用~表示
    password: ${SECURITY_USER_PASSWORD}
    database: 0
    timeout: 30s
    lettuce:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        #等待可用连接的最大时间，负数为不限制
        max-wait: -1s
        # 最大活跃连接数，负数为不限制
        max-active: -1
eureka_server: http://admin:${SECURITY_USER_PASSWORD}@wk-server:2001/eureka/,http://admin:${SECURITY_USER_PASSWORD}@jr-server:2002/eureka/,http://admin:${SECURITY_USER_PASSWORD}@lj-server:2003/eureka/
security:
  user:
    name: admin
    password: ${SECURITY_USER_PASSWORD}
# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true
