spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mysql
    url: jdbc:mysql://192.168.159.128:3306/sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.159.128
    port: 5672
    username: admin
    password: admin
  redis:
    host: 192.168.159.128
    port: 6379
  jpa:
    show-sql: true
