spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${mysqlserver:jr-server}:3306/fw-sys?characterEncoding=utf-8&useSSL=false
