spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${mysqlserver:jr-server}:3306/sys?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
mybatis:
# 指定实体类包路径	
  typeAliasesPackage: com.wk.*.*.model
# 指定xml文件扫描路径 
  mapper-locations: classpath*:mapper/*.xml
