
spring:
    name: oauth2-server
    security:
        oauth2:
            client:
                registration:
                    test:
                        client-id: test
                        client-secret: '{bcrypt}$2a$10$tMSDLeQjFehV8Z1BxoU3quISNyLXXMDI8pdA3RKdwqv1ujuZ6AAQG'
                        scope: select
                        authorization-grant-type: password,refresh_token,client_credentials,authorization_code
                        accessTokenValiditySeconds: 600
                        refreshTokenValiditySeconds: 600
                    dev:
                        client-id: dev
                        client-secret: '{bcrypt}$2a$10$tMSDLeQjFehV8Z1BxoU3quISNyLXXMDI8pdA3RKdwqv1ujuZ6AAQG'
                        scope: select
                        authorization-grant-type: client_credentials
                        accessTokenValiditySeconds: 600
                        refreshTokenValiditySeconds: 600


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
