---
spring:
    name: oauth2-server
    security:
        oauth2:
            client:
                registration:
                    test:
                        client-id: test
                        client-secret: '{bcrypt}$2a$10$3AERFonhGzRIh2qMv/jtL.S38so5sxzdsAhyzqMtSLgoNZGiQL3Im'
                        scope: select
                        authorizationGrantType: password,refresh_token,client_credentials,authorization_code
                        authoritie: [oauth2]
                        accessTokenValiditySeconds: 600
                        refreshTokenValiditySeconds: 600
                    dev:
                        client-id: dev
                        client-secret: '{bcrypt}$2a$10$3AERFonhGzRIh2qMv/jtL.S38so5sxzdsAhyzqMtSLgoNZGiQL3Im'
                        scope: select
                        authorizationGrantType: client_credentials
                        authoritie: [oauth2]
                        accessTokenValiditySeconds: 600
                        refreshTokenValiditySeconds: 600
...
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://${mysqlserver:jr-server}:3306/oauth?characterEncoding=utf-8&useSSL=false&useUnicode=true&serverTimezone=Asia/Shanghai
mybatis:
  # 指定实体类包路径	
  typeAliasesPackage: com.wk.*.model
  config-location: classpath:mybatis-config.xml
  # 指定xml文件扫描路径 
  mapper-locations: lasspath*:mapper/**Mapper.xml
  #configuration:
    #进行自动映射时，数据以下划线命名，如数据库返回的"order_address"命名字段是否映射为class的"orderAddress"字段。默认为false
    #map-underscore-to-camel-case: true
....
---
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
...
