spring:
    application:
        author:
            address: shanghai
        name: zuul-1

zuul:
    # 过滤service服务
    #ignoredServices: '*-server-*'
    ignoredPatterns:
        /**/auth/loadUserByUsername,/**/auth/loadUserByMobile
    routes:
        sys:
            path: /sys12/**
            sensitiveHeaders:
            serviceId: sys
        oauth:
            path: /oauth12/**
            sensitiveHeaders:
            serviceId: oauth2
    sensitive-headers: Cookie,Set-Cookie
    upload:
        multipart:
            max-file-size: 100MB #设置文件最大数据大小
            max-request-size: 100MB #设置总上传数据大小
