spring:
  application:
    name: zuul
    author: wkk

zuul:
  sensitive-headers: Cookie,Set-Cookie
  upload:
    multipart:
      max-file-size: 100MB #设置文件最大数据大小
      max-request-size: 100MB #设置总上传数据大小